app: # subscription-aggregator-service 1.0
  log:
    enabled: true
    level: "INFO" # Options are "DEBUG", "INFO", "WARN", "ERROR"
    log2file: true
    file_path: "application.log"
    log_format: "text" # Options are "text", "json"
  api:
    host: "localhost"
    port: 8080
    base_path: "/api/v1"
    gin_release_mode: true
  database:
    host: "localhost"
    port: 5432
    user: "username"
    password: "password"
    database_name: "subscription-aggregator-service"
    ssl_mode: "disable" # Options are ... //TODO: _
